const state={status:null,settings:null,view:'overview',sessionFilter:'all'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const eventNames={started:'监控器启动',paused:'监控器暂停',resumed:'监控器恢复','capacity-detected':'检测到容量错误','retry-clicked':'已点击重试','retry-invoked':'已触发重试','retry-confirmed':'重试成功','retry-failed':'重试失败','retry-unconfirmed':'确认超时','limit-reached':'达到重试上限','retry-candidate':'发现候选 turn','ui-yield':'UI 租约让出'};
const eventKind=e=>e==='retry-confirmed'||e==='started'||e==='resumed'?'good':e.includes('failed')||e.includes('unconfirmed')||e==='limit-reached'?'bad':e.includes('capacity')?'warn':'';
const fmtTime=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function json(url,options){const r=await fetch(url,options);if(!r.ok)throw new Error(await r.text());return r.json()}
async function refresh(){try{state.status=await json('/api/status');render();$('#serviceText').textContent=state.status.monitor.running?(state.status.monitor.paused?'已暂停':'运行中'):'已停止';$('#lastSync').textContent=`同步于 ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`}catch(e){$('#serviceText').textContent='无法连接';$('#lastSync').textContent='API 未响应'}}
function getRecordedSessions(){return(s=>s.filter(x=>x.hasRecord!==false).sort((a,b)=>(Date.parse(b.lastEventAt)||0)-(Date.parse(a.lastEventAt)||0)))(state.status?.sessions||[])}
function renderSessionRows(){let rows=getRecordedSessions();if(state.sessionFilter==='failed')rows=rows.filter(x=>x.failures>0);if(state.sessionFilter==='recent')rows=rows.slice(0,20);$('#sessionRows').innerHTML=rows.map(sessionTableRow).join('')||'<div class="empty">暂无符合条件的记录</div>'}
function render(){const s=state.status;if(!s)return;const t=s.total;$('#metricSessions').textContent=t.sessions;$('#metricErrors').textContent=t.capacityErrors;$('#metricSuccesses').textContent=t.successes;$('#metricFailures').textContent=t.failures;$('#successRate').textContent=t.successes+t.failures?`成功率 ${Math.round(t.successes/(t.successes+t.failures)*100)}%`:'成功率 —';$('#historyNote').textContent=`${s.history.note}。最近事件：${fmtTime(s.history.lastEventAt)}。`;
 const paused=s.monitor.paused,running=s.monitor.running;$('#monitorBadge').className=`badge ${running&&!paused?'':'stopped'}`;$('#monitorBadge').innerHTML=`<i></i>${!running?'监控器已停止':paused?'监控器已暂停':'监控器运行中'}`;$('#mainControl').textContent=!running?'启动监控':paused?'恢复监控':'暂停监控';
 $('#overviewSessions').innerHTML=s.sessions.slice(0,5).map(sessionCard).join('')||'<div class="empty">还没有可展示的会话</div>';$('#overviewEvents').innerHTML=s.recent.slice(0,6).map(eventRow).join('')||'<div class="empty">等待监控器写入事件</div>';renderSessionRows();$('#activityRows').innerHTML=s.recent.length?s.recent.slice().reverse().map(activityRow).join(''):'<div class="empty">暂无活动</div>';
}
function sessionCard(x){const status=x.failures?'failure':x.successes?'success':'';return`<button class="session-row" data-session="${esc(x.id)}"><div class="session-name"><strong>${esc(x.title)}</strong><span>最后活动 ${fmtTime(x.lastEventAt)}</span></div><span class="status-pill ${status}">${x.failures?esc(x.lastError):x.successes?'已恢复':x.lastEvent==='capacity-detected'?'待处理':'监听中'}</span><span class="session-count">${x.capacityErrors} 次错误</span></button>`}
function sessionTableRow(x){return`<button class="table-row" data-session="${esc(x.id)}"><div class="row-title"><strong>${esc(x.title)}</strong><span>${esc(x.id)}</span></div><span>${x.capacityErrors}</span><span><b class="good-text">${x.successes}</b> / <b class="bad-text">${x.failures}</b></span><span class="${x.failures?'bad-text':x.successes?'good-text':'muted-text'}">${esc(x.failures?x.lastError:x.successes?'已恢复':'监听中')}</span><span class="muted-text">${fmtTime(x.lastEventAt)}</span></button>`}
function eventRow(x){const kind=eventKind(x.event);return`<div class="event-row"><i class="event-dot ${kind}"></i><div class="event-copy"><strong>${esc(eventNames[x.event]||x.event)}</strong><span>${esc(x.session||'系统')} · ${fmtTime(x.timestamp)}${x.detail?' · '+esc(x.detail):''}</span></div></div>`}
function activityRow(x){return`<div class="activity-item"><span class="activity-time">${fmtTime(x.timestamp)}</span><span class="activity-event">${esc(eventNames[x.event]||x.event)}</span><span class="activity-detail">${esc(x.session||'系统')}${x.detail?' · '+esc(x.detail):''}</span></div>`}
function openSession(id){const x=state.status.sessions.find(v=>v.id===id);if(!x)return;$('#drawerContent').innerHTML=`<span class="eyebrow">SESSION DETAIL</span><h2>${esc(x.title)}</h2><p class="drawer-subtitle">${esc(x.id)}<br/>首次检测 ${fmtTime(x.firstSeen)} · 最后活动 ${fmtTime(x.lastEventAt)}</p><div class="drawer-stat"><div><span>容量错误</span><strong>${x.capacityErrors}</strong></div><div><span>成功</span><strong class="good-text">${x.successes}</strong></div><div><span>失败</span><strong class="bad-text">${x.failures}</strong></div></div><span class="eyebrow">TIMELINE</span><div class="timeline">${x.timeline.slice().reverse().map(t=>`<div class="timeline-item"><strong>${esc(eventNames[t.event]||t.event)}</strong><span>${fmtTime(t.at)}${t.detail?' · '+esc(t.detail):''}</span>${t.reason?`<span class="reason">${esc(t.reason)}</span>`:''}</div>`).join('')||'<div class="empty">暂无详情</div>'}</div>`;$('#drawerBackdrop').classList.remove('hidden')}
function switchView(view){state.view=view;$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==`view-${view}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#pageTitle').textContent={overview:'监控概览',sessions:'监听会话',activity:'活动记录',settings:'设置'}[view]||'监控概览'}
async function control(action){const b=$('#mainControl');b.disabled=true;try{await json('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});await refresh()}finally{b.disabled=false}}
async function loadSettings(){try{const r=await json('/api/settings');state.settings=r.settings;$('#autostartToggle').checked=r.autostart;$('#nativeClick').checked=!!r.settings.allowNativeClick;$('#logRoot').value=(r.settings.logRoot||[])[0]||'';$('#cooldownSeconds').value=r.settings.cooldownSeconds;$('#maxRetries').value=r.settings.maxRetries;$('#retryConfirmSeconds').value=r.settings.retryConfirmSeconds;$('#retryUiWaitSeconds').value=r.settings.retryUiWaitSeconds;$('#pollSeconds').value=r.settings.pollSeconds;$('#rescanSeconds').value=r.settings.rescanSeconds;$('#uiLeaseSeconds').value=r.settings.uiLeaseSeconds;$('#backoffSeconds').value=(r.settings.backoffSeconds||[]).join(',');$('#processName').value=(r.settings.processName||[]).join(',')}catch(e){}}
async function saveSettings(){const x=state.settings||{};x.logRoot=[$('#logRoot').value.trim()];x.processName=$('#processName').value.split(',').map(v=>v.trim()).filter(Boolean);x.maxRetries=Number($('#maxRetries').value)||0;x.cooldownSeconds=Number($('#cooldownSeconds').value)||0;x.retryConfirmSeconds=Number($('#retryConfirmSeconds').value)||30;x.retryUiWaitSeconds=Number($('#retryUiWaitSeconds').value)||90;x.pollSeconds=Number($('#pollSeconds').value)||.25;x.rescanSeconds=Number($('#rescanSeconds').value)||60;x.uiLeaseSeconds=Number($('#uiLeaseSeconds').value)||5;x.backoffSeconds=$('#backoffSeconds').value.split(',').map(v=>Number(v.trim())).filter(v=>Number.isFinite(v)&&v>=0);x.allowNativeClick=$('#nativeClick').checked;await json('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings:x,autostart:$('#autostartToggle').checked})});await refresh();alert('设置已保存，监控器已重启。')}
$('#mainControl').addEventListener('click',()=>{const m=state.status?.monitor;if(!m||!m.running)control('start');else control(m.paused?'resume':'pause')});$('#refreshButton').addEventListener('click',refresh);$('#heroSettings').addEventListener('click',()=>switchView('settings'));$('#saveSettings').addEventListener('click',saveSettings);$('#drawerClose').addEventListener('click',()=>$('#drawerBackdrop').classList.add('hidden'));$('#drawerBackdrop').addEventListener('click',e=>{if(e.target.id==='drawerBackdrop')$('#drawerBackdrop').classList.add('hidden')});$$('.nav-item').forEach(x=>x.addEventListener('click',()=>{switchView(x.dataset.view);if(x.dataset.view==='settings')loadSettings()}));$$('[data-view-link]').forEach(x=>x.addEventListener('click',()=>switchView(x.dataset.viewLink)));document.addEventListener('click',e=>{const x=e.target.closest('[data-session]');if(x)openSession(x.dataset.session)});$('#themeToggle').addEventListener('click',()=>{document.documentElement.classList.toggle('theme-light');localStorage.setItem('retry-theme',document.documentElement.classList.contains('theme-light')?'light':'dark')});if(localStorage.getItem('retry-theme')==='light')document.documentElement.classList.add('theme-light');loadSettings();refresh();setInterval(refresh,5000);
$$('[data-session-filter]').forEach(x=>x.addEventListener('click',()=>{state.sessionFilter=x.dataset.sessionFilter;$$('[data-session-filter]').forEach(b=>b.classList.toggle('active',b===x));renderSessionRows()}));$('#themeToggle').addEventListener('click',()=>{document.documentElement.classList.toggle('theme-light');localStorage.setItem('retry-theme',document.documentElement.classList.contains('theme-light')?'light':'dark')});if(localStorage.getItem('retry-theme')==='light')document.documentElement.classList.add('theme-light');loadSettings();refresh();setInterval(refresh,5000);
